"""Initial migration.

Revision ID: 161fc2431e53
Revises: 
Create Date: 2022-03-07 15:39:02.048953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161fc2431e53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('path_to_photo', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('activation_uuid', sa.String(), nullable=True),
    sa.Column('activation_uuid_date', sa.DateTime(), nullable=True),
    sa.Column('restore_uuid', sa.String(), nullable=True),
    sa.Column('restore_uuid_date', sa.DateTime(), nullable=True),
    sa.Column('vk_id', sa.Integer(), nullable=True),
    sa.Column('google_id', sa.Numeric(precision=21, scale=0), nullable=True),
    sa.Column('new_email', sa.String(), nullable=True),
    sa.Column('email_update_uuid', sa.String(), nullable=True),
    sa.Column('email_update_uuid_date', sa.DateTime(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
